version: '3'
services:
    Client-demo:
        image: builder-client
        build:
            context: builder-client/.
            dockerfile: Dockerfile
        ports:
          - 8080:8080
    Public-demo:    
        image: builder-public
        build:
            context: builder-public/.
            dockerfile: Dockerfile
        ports:
          - 9080:9080
