version: '3'
services:
    client-demo:
        build:
            context: builder-client/.
            dockerfile: Dockerfile
        ports:
          - 8080:8080
    public-demo:    
        build:
            context: builder-public/.
            dockerfile: Dockerfile
        ports:
          - 9080:9080
